version: '3'

x-common-config:
  &common-config
  image: apache/ozone-runner:${OZONE_RUNNER_VERSION}
  volumes:
    - /opt/ozone/ozone-1.2.1:/opt/hadoop
  env_file:
    - /opt/ozone/ozone-1.2.1/compose/ozone/docker-config

x-layout_version:
  &metadata_layout
  OZONE-SITE.XML_ozone.om.metadata.layout: ${OZONE_OM_METADATA_LAYOUT:-SIMPLE}
  OZONE-SITE.XML_ozone.om.enable.filesystem.paths: "${OZONE_OM_ENABLE_FILESYSTEM_PATHS:-false}"

x-replication:
  &replication
  OZONE-SITE.XML_ozone.replication: ${OZONE_REPLICATION_FACTOR:-1}
services:
  trinodb:
    image: trinodb/trino:379
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./trino/etc:/etc/trino/
    links:
      - s3g


  reachops-hive-metastore:
    image: techneural/reachops-hive-metastore:0.0.1
    restart: always
    environment:
      METASTORE_DB: mysql
    entrypoint: /entrypoint.sh
    depends_on:
      - hive-repo-mysql
    expose:
      - 9083
    volumes:
      - ./reachops-hive-metastore/etc/metastore-site.xml:/opt/apache-hive-metastore/conf/metastore-site.xml
    links:
      - s3g

  hive-repo-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: reachops
      MYSQL_PASSWORD: reachops
      MYSQL_DATABASE: hive-repo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./reachops-hive-metastore/data:/var/lib/mysql
    expose:
      - 3306
  datanode:
    <<: *common-config
    ports:
      - 9864
      - 9882
    environment:
      <<: *replication
      <<: *metadata_layout
      OZONE_OPTS:
    command: ["ozone","datanode"]
  om:
    <<: *common-config
    environment:
      ENSURE_OM_INITIALIZED: /data/metadata/om/current/VERSION
      OZONE_OPTS:
      <<: *replication
      <<: *metadata_layout
    ports:
      - 9874:9874
      - 9862:9862
    command: ["ozone","om"]
  scm:
    <<: *common-config
    ports:
      - 9876:9876
      - 9860:9860
    environment:
      ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
      OZONE-SITE.XML_hdds.scm.safemode.min.datanode: ${OZONE_SAFEMODE_MIN_DATANODES:-1}
      OZONE_OPTS:
      <<: *replication
      <<: *metadata_layout
    command: ["ozone","scm"]
  s3g:
    <<: *common-config
    environment:
      OZONE_OPTS:
      <<: *replication
      <<: *metadata_layout
    ports:
      - 9878:9878
    command: ["ozone","s3g"]
  recon:
    <<: *common-config
    ports:
      - 9888:9888
    environment:
      OZONE_OPTS:
      <<: *replication
      <<: *metadata_layout
    command: ["ozone","recon"]
