version: '3'

services:
  trinodb:
    image: trinodb/trino:379
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./trino/etc:/etc/trino/
    links:
      - reachops-hive-metastore
      - ozone-s3

  reachops-hive-metastore:
    image: techneural/reachops-hive-metastore:0.0.1
    restart: always
    entrypoint: entrypoint.sh
    depends_on:
      - hive-repo-mysql
    expose:
      - 9083
    volumes:
      - ./reachops-hive-metastore/etc/metastore-site.xml:/opt/apache-hive-metastore/conf/metastore-site.xml
    links:
      - ozone-s3

  hive-repo-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: reachops
      MYSQL_PASSWORD: reachops
      MYSQL_DATABASE: hive-repo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./reachops-hive-metastore/data:/var/lib/mysql
    expose:
      - 3306

  ozone-s3:
    image: apache/ozone:latest
    restart: always
      - 9876:9876
    volumes:
      - ./reachops-hive-metastore/data:/var/lib/mysql
    expose:
      - 9878
